### PR TITLE
Removes sign in with username/password, update sample to use OAuth authorization code grant 

### PR DESCRIPTION
**Pull request by marnberg**
Updates default service endpoint
Removed deprecated functions and classes

### CODE REVIEW

**Review by jrmiddle — APPROVED** [review]

**Review by jrmiddle — CHANGES_REQUESTED** [review]
Hey @marnberg , unfortunately I think we need to retain the ability for users to log in using username/password, for AWS. It's definitely deprecated usage, but we need to retain it for now.

It *may* make sense to move the legacy SDK into a separate "maint" branch or something, so that we have an older version and a newer version, differentiated by semver. Open to your thoughts about that.

I know, it's a PITA.

**Comment by jeffMeador** [comment]
@jrmiddle can you clarify what usage is deprecated? We utilize a these functions for Afero accounts and these would be breaking changes to remove `createAccount`, `getAccessToken`,`sendPasswordRecoveryEmail`, `resetPasswordWithCode`, etc. and I wasn't aware any of that was going to be deprecated.

**Comment by marnberg** [comment]
All new deployments that connect to https://api2.afero.net will need to authenticate with authorization grant through OAuth 2.0. As far as I know the removed functions are not compatible with the service on https://api2.afero.net so leaving them in as depreciated would be confusing and broken. A maintenance branch only makes sense once there is any maintenance updates needed for AWS.

**Comment by jrmiddle** [comment]
@jeffMeador Apologies for the inside baseball. For future cloud deployments, we're migrating to a new OAuth 2 broker (keycloak), and as part of that process there will be some SDK changes. That said, these do not apply to the AWS cloud, hence my comments on this PR.

**Pull request closed without merging**
